### ISSUE TITLE
Only add access-control-allow-origin:* if no access-control-allow-origin exists

### ISSUE THREAD

**Issue by SoniEx2** [spenibus/cors-everywhere-firefox-addon#33]
basically just to make the extension safe for general use.

**Comment by spenibus** [comment]
That would prevent the addon from overriding headers which do not allow your origin, which seems counter to its purpose.

I might also add that "safe for general use" is conceptually at odds with what we're doing here, so I'm curious as to what issue we're trying to solve.

Perhaps you could present some use-case to better explain how this is an improvement and how it won't bring people here to complain that the addon stopped working if such a change was implemented.

**Comment by SoniEx2** [comment]
the reason ACAO:* isn't the default is because someone decided corporate networks are good, and webfont DRM (... which is a result of those not being cross-origin by default (i.e. unlike images and scripts and whatnot), rather than the other way around).

this change probably wouldn't cover every use-case, but it'd be a safe default for users not on a corporate network. we can then rebrand the extension "DRMTools" and get webapps to use it like they used to use flash and java.

**Comment by spenibus** [comment]
You do realize this a development tool meant for developers ? It's not something to be used permanently like `https everywhere` and certainly not by the general populace.

The sole purpose of this extension is to completely ignore CORS as much as possible.

Safety is literally not a concern because, again, the user-base is supposed to be developers.

I honestly don't see how this would improve rather than limit the core functionality of the addon.

**Comment by SoniEx2** [comment]
it'd help make the addon less necessary.

**Comment by spenibus** [comment]
If that's the goal, your best bet is to go to the W3C and tell them CORS was a poorly thought idea and they should feel bad about it.
