### ISSUE TITLE
What is the latest Version number of this ?

### ISSUE THREAD

**Issue by nndp** [spenibus/cors-everywhere-firefox-addon#8]
Hello spenibus, I need to add this Tool to my Project Documentation of used tools, but I can't find any version number. Could you help me out ?

**Comment by spenibus** [comment]
You can find the version number within the file `./install.rdf`, in the property `em:version`. This is used by Firefox and can be seen in the addon description page within the browser.

Latest version is `20160122-2027`, however the package hosted by Mozilla is still `20150910-1410`, since the recent commits were minor.
